### ISSUE TITLE
Cannot disable javascript build

### ISSUE THREAD

**Issue by parisholley** [51Degrees/pipeline-node#3]
https://github.com/51Degrees/pipeline-node/blob/d544e17ebc930adbec313b0db797b65cf2dfa4f1/fiftyone.pipeline.core/pipelineBuilder.js#L54

Not sure the original intent of this if statement, but there is no way to turn off javascript building. This being enabled is a massive performance decrease.

**Comment by Steve51D** [comment]
Thanks @parisholley , you're right, this should certainly be optional. Thanks for the heads up, we'll add this to the changes for a future release.

**Comment by tungntpham** [comment]
Hi @parisholley. This is just an update. we will include this fix in the 4.2.1 release.

**Comment by tungntpham** [comment]
Hi @parisholley. The 4.2.1version is now released. Please have try and let us know if the issue has been resolved. Many thanks.
